name: CI
on:
  push:
    branches: [ main, dev, cut-cookie ]
  pull_request:
    branches:
      - '**'
# jobs:

#   gcc-debug:
#     name: Unit Tests (gcc, debug mode)
#     runs-on: ubuntu-20.04
#     env:
#       CXX: g++
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           submodules: 'recursive'
      # Adapted from https://askubuntu.com/a/524368
      # - run: echo $(hostname -I | cut -d\  -f1) $(hostname) | sudo -h 127.0.0.1 tee -a /etc/hosts
      # - uses: docker-practice/actions-setup-docker@v1
      # - run: docker build -t amlalejini/directed-digital-evolution .
      # - run: docker ps -a
      # - run: docker run -e "CXX=${CXX}" --cap-add=SYS_ADMIN -e "CXX=${CXX}" -i amlalejini/directed-digital-evolution /bin/bash -c "set -x && cd /opt/directed-digital-evolution/tests && make"
